# Generated by Django 5.2.15 on 2026-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatamis', '0004_tatami_active_results_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatami',
            name='scoreboard_connected',
            field=models.BooleanField(default=False, verbose_name='Статус підключення табло'),
        ),
        migrations.AddField(
            model_name='tatami',
            name='scoreboard_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса апаратного табло'),
        ),
    ]
