# Generated by Django 5.2.15 on 2026-06-22 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0016_tournament_refund_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID інвойсу Monobank')),
                ('payment_type', models.CharField(choices=[('registrations', 'Внески за участь'), ('platform_fee', 'Комісія платформи')], default='registrations', max_length=20, verbose_name='Тип оплати')),
                ('amount', models.PositiveIntegerField(verbose_name='Сума до сплати (UAH)')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Сплачено'), ('expired', 'Скасовано/Термін закінчився'), ('failed', 'Помилка оплати')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на оплату')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('registrations', models.ManyToManyField(blank=True, related_name='payment_invoices', to='tournaments.registration', verbose_name='Реєстрації')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='tournaments.tournament', verbose_name='Турнір')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Платник')),
            ],
            options={
                'verbose_name': 'Рахунок на оплату',
                'verbose_name_plural': 'Рахунки на оплату',
                'db_table': 'billing_payment_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('registrations', 'Внески за участь'), ('platform_fee', 'Комісія платформи')], max_length=20, verbose_name='Тип оплати')),
                ('transaction_type', models.CharField(choices=[('payment', 'Оплата'), ('refund', 'Повернення')], default='payment', max_length=20, verbose_name='Тип транзакції')),
                ('amount', models.IntegerField(verbose_name='Сума (UAH)')),
                ('method', models.CharField(choices=[('online', 'Онлайн (Monobank)'), ('offline', 'Офлайн (Готівка)')], default='online', max_length=20, verbose_name='Спосіб оплати')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Референс транзакції')),
                ('monobank_receipt_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID квитанції Monobank')),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на офіційну квитанцію')),
                ('requires_refund', models.BooleanField(default=False, help_text='Флаг конфлікту оплати (подвійний платіж)', verbose_name='Потребує повернення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакції')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='billing.paymentinvoice', verbose_name='Рахунок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Платник')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'db_table': 'billing_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
