# Generated by Django 5.2.15 on 2026-06-23 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_transaction_invoice'),
        ('tournaments', '0015_alter_category_bracket_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сума виплати (UAH)')),
                ('bank_details', models.CharField(max_length=255, verbose_name='Банківські реквізити (IBAN / Карта)')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('completed', 'Виплачено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Запит на виплату',
                'verbose_name_plural': 'Запити на виплату',
                'db_table': 'billing_payout_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
