# Generated by Django 5.2.14 on 2026-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payoutrequest'),
        ('tournaments', '0016_tournament_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='bulk_fee_invoices', to='tournaments.tournament', verbose_name='Турніри для оплати комісії'),
        ),
    ]
