# Generated by Django 5.2.15 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_paymentinvoice_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN отримувача'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Призначення платежу'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='recipient_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Код ЄДРПОУ / ІПН отримувача'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ПІБ отримувача / Назва організації'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Посилання на оплату'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_details',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Банківські реквізити (Картка/Реквізити)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='monobank_receipt_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID квитанції Monobank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Посилання на офіційну квитанцію'),
        ),
    ]
