# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_index', models.PositiveSmallIntegerField(help_text='1 = перший раунд, 2 = 1/8, 3 = 1/4 тощо', verbose_name='Номер раунду')),
                ('match_order', models.PositiveSmallIntegerField(verbose_name='Порядковий номер у раунді')),
                ('tatami_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер татамі')),
                ('score_first', models.IntegerField(default=0, verbose_name='Бали учасника 1')),
                ('score_second', models.IntegerField(default=0, verbose_name='Бали учасника 2')),
                ('warnings_first', models.IntegerField(default=0, verbose_name='Попередження уч. 1')),
                ('warnings_second', models.IntegerField(default=0, verbose_name='Попередження уч. 2')),
                ('win_method', models.CharField(blank=True, choices=[('ippon', 'Іппон'), ('decision', 'За рішенням суддів'), ('disqualification', 'Дискваліфікація'), ('walkover', 'Неявка суперника'), ('withdrawal', 'Знято з поєдинку')], max_length=100, verbose_name='Спосіб перемоги')),
                ('match_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (сек)')),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('ongoing', 'Триває'), ('completed', 'Завершено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.category', verbose_name='Категорія')),
                ('loser_next_match', models.ForeignKey(blank=True, help_text='Для double elimination (у MVP не використовується)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_prev_matches', to='matches.match', verbose_name='Матч для того, хто програв')),
                ('next_match', models.ForeignKey(blank=True, help_text='Ключ рекурсивного дерева сітки. Null → фінал.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches', to='matches.match', verbose_name='Наступний матч')),
                ('reg_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_first', to='tournaments.registration', verbose_name='Учасник 1')),
                ('reg_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_second', to='tournaments.registration', verbose_name='Учасник 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.registration', verbose_name='Переможець')),
            ],
            options={
                'verbose_name': 'Поєдинок',
                'verbose_name_plural': 'Поєдинки',
                'db_table': 'match',
                'ordering': ['category', 'round_index', 'match_order'],
                'indexes': [models.Index(fields=['category', 'round_index', 'match_order'], name='idx_match_bracket_pos'), models.Index(fields=['status'], name='idx_match_status')],
            },
        ),
    ]
