# Generated by Django 5.2.14 on 2026-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='flags_aka',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Прапори Aka (Kata)'),
        ),
        migrations.AddField(
            model_name='match',
            name='flags_ao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Прапори Ao (Kata)'),
        ),
        migrations.AddField(
            model_name='match',
            name='judges_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість суддів (Kata)'),
        ),
        migrations.AddField(
            model_name='match',
            name='senshu',
            field=models.CharField(choices=[('none', 'None'), ('aka', 'Aka'), ('ao', 'Ao')], default='none', max_length=4, verbose_name='Senshu (перша атака)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_method',
            field=models.CharField(blank=True, choices=[('decision', 'За рішенням суддів'), ('disqualification', 'Дискваліфікація'), ('walkover', 'Неявка суперника'), ('withdrawal', 'Знято з поєдинку'), ('points', 'За очками'), ('hantei', 'Hantei (рішення суддів)'), ('hansoku', 'Hansoku (дискваліфікація)'), ('kiken', 'Kiken (відмова від участі)'), ('ippon', 'Ippon'), ('wazaari', 'Waza-ari')], max_length=100, verbose_name='Спосіб перемоги'),
        ),
    ]
