# Generated by Django 5.2.14 on 2026-05-19 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_add_senshu_flags_judges_win_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Порядковий номер події')),
                ('event_type', models.CharField(choices=[('score', 'Нарахування балів'), ('warning', 'Попередження'), ('senshu', 'Сенсю'), ('flags_decision', 'Рішення прапорами (Kata)'), ('finish', 'Завершення поєдинку'), ('start', 'Початок поєдинку'), ('reset', 'Скидання стану')], max_length=20, verbose_name='Тип події')),
                ('payload', models.JSONField(default=dict, verbose_name='Дані події')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_events', to=settings.AUTH_USER_MODEL, verbose_name='Суддя')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='Поєдинок')),
            ],
            options={
                'verbose_name': 'Подія поєдинку',
                'verbose_name_plural': 'Події поєдинку',
                'db_table': 'match_event',
                'ordering': ['match', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('match', 'sequence'), name='uq_match_event_sequence')],
            },
        ),
    ]
