# Generated by Django 5.2.14 on 2026-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_add_timer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('score', 'Нарахування балів'), ('warning', 'Попередження'), ('senshu', 'Сенсю'), ('flags_decision', 'Рішення прапорами (Kata)'), ('finish', 'Завершення поєдинку'), ('start', 'Початок поєдинку'), ('reset', 'Скидання стану'), ('timer_start', 'Старт таймера'), ('timer_pause', 'Пауза таймера'), ('timer_resume', 'Продовження таймера'), ('timer_reset', 'Скидання таймера'), ('timer_set_dur', 'Зміна тривалості')], max_length=20, verbose_name='Тип події'),
        ),
    ]
