# Generated by Django 5.2.14 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='win_method',
            field=models.CharField(blank=True, choices=[('decision', 'За рішенням суддів'), ('disqualification', 'Дискваліфікація'), ('walkover', 'Неявка суперника'), ('withdrawal', 'Знято з поєдинку'), ('points', 'За очками'), ('hantei', 'Hantei (рішення суддів)'), ('hansoku', 'Hansoku (дискваліфікація)'), ('kiken', 'Kiken (відмова від участі)'), ('ippon', 'Ippon'), ('wazaari', 'Waza-ari'), ('draw', 'Нічия')], max_length=100, verbose_name='Спосіб перемоги'),
        ),
    ]
