# Generated by Django 5.2.15 on 2026-06-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_tournament_fields_category_optional_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='show_timer',
            field=models.BooleanField(default=False, verbose_name='Показувати таймер'),
        ),
    ]
