# Generated by Django 5.2.15 on 2026-06-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_patronymic_athlete_photo_team'),
        ('matches', '0009_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='athlete_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_first_athlete', to='athletes.athlete', verbose_name='Атлет Aka'),
        ),
        migrations.AddField(
            model_name='match',
            name='athlete_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_second_athlete', to='athletes.athlete', verbose_name='Атлет Ao'),
        ),
        migrations.AddField(
            model_name='match',
            name='bout_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер бою у зустрічі'),
        ),
        migrations.AddField(
            model_name='match',
            name='parent_team_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_bouts', to='matches.match', verbose_name='Командна зустріч'),
        ),
    ]
