# Generated by Django 5.2.14 on 2026-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_athlete_first_match_athlete_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_bracket_reset',
            field=models.BooleanField(default=False, verbose_name='Супер-фінал (Bracket Reset)'),
        ),
    ]
