# Generated by Django 5.2.15 on 2026-06-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_is_bracket_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='Стан поєдинку'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('score', 'Нарахування балів'), ('warning', 'Попередження'), ('senshu', 'Сенсю'), ('flags_decision', 'Рішення прапорами (Kata)'), ('finish', 'Завершення поєдинку'), ('start', 'Початок поєдинку'), ('reset', 'Скидання стану'), ('timer_start', 'Старт таймера'), ('timer_pause', 'Пауза таймера'), ('timer_resume', 'Продовження таймера'), ('timer_reset', 'Скидання таймера'), ('timer_set_dur', 'Зміна тривалості'), ('timer_toggle', 'Відображення таймера'), ('judges_count_change', 'Зміна кількості суддів'), ('ruleset_event', 'Подія правил')], max_length=20, verbose_name='Тип події'),
        ),
    ]
