# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('gender', models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=10, verbose_name='Стать')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('base_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Базова вага (кг)')),
                ('skill_level', models.CharField(blank=True, help_text='Напр., «Чорний пояс 1 дан»', max_length=50, verbose_name='Рівень майстерності')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='accounts.club', verbose_name='Клуб')),
                ('coach', models.ForeignKey(help_text='Відповідальний тренер (користувач з роллю coach)', on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмени',
                'db_table': 'athlete',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['club'], name='idx_athlete_club'), models.Index(fields=['coach'], name='idx_athlete_coach')],
            },
        ),
    ]
