# Generated by Django 5.2.14 on 2026-06-12 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_patronymic_user_photo_alter_club_region_and_more'),
        ('athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва команди')),
                ('athletes', models.ManyToManyField(related_name='teams', to='athletes.athlete', verbose_name='Склад команди')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.club', verbose_name='Клуб')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
                'db_table': 'team',
            },
        ),
    ]
