# Generated by Django 5.2.14 on 2026-06-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_patronymic_athlete_photo_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteWeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вага (кг)')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата фіксації')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Лог ваги спортсмена',
                'verbose_name_plural': 'Логи ваги спортсменів',
                'db_table': 'athlete_weight_log',
                'ordering': ['-logged_at'],
            },
        ),
    ]
