# Generated by Django 5.2.14 on 2026-06-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(blank=True, choices=[('vinnytsia', 'Вінницька область'), ('volyn', 'Волинська область'), ('dnipro', 'Дніпропетровська область'), ('donetsk', 'Донецька область'), ('zhytomyr', 'Житомирська область'), ('zakarpattia', 'Закарпатська область'), ('zaporizhzhia', 'Запорізька область'), ('ivano-frankivsk', 'Івано-Франківська область'), ('kyiv_oblast', 'Київська область'), ('kyiv_city', 'м. Київ'), ('kirovohrad', 'Кіровоградська область'), ('luhansk', 'Луганська область'), ('lviv', 'Львівська область'), ('mykolaiv', 'Миколаївська область'), ('odesa', 'Одеська область'), ('poltava', 'Полтавська область'), ('rivne', 'Рівненська область'), ('sumy', 'Сумська область'), ('ternopil', 'Тернопільська область'), ('kharkiv', 'Харківська область'), ('kherson', 'Херсонська область'), ('khmelnytskyi', 'Хмельницька область'), ('cherkasy', 'Черкаська область'), ('chernivtsi', 'Чернівецька область'), ('chernihiv', 'Чернігівська область'), ('crimea', 'АР Крим'), ('sevastopol', 'м. Севастополь')], max_length=150, verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Організатор'), ('coach', 'Тренер'), ('judge', 'Суддя'), ('admin', 'Адміністратор'), ('spectator', 'Глядач'), ('staff', 'Персонал')], default='spectator', max_length=50, verbose_name='Роль'),
        ),
    ]
