# Generated by Django 5.2.14 on 2026-06-22 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_patronymic_user_photo_alter_club_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email підтверджено'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='referee_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Суддівська категорія'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рівень майстерності (пояс/дан)'),
        ),
        migrations.CreateModel(
            name='EmailConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код підтвердження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('expires_at', models.DateTimeField(verbose_name='Дійсний до')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation_code', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Код підтвердження email',
                'verbose_name_plural': 'Коди підтвердження email',
                'db_table': 'email_confirmation_code',
            },
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('organizer', 'Організатор'), ('coach', 'Тренер'), ('judge', 'Суддя'), ('admin', 'Адміністратор'), ('spectator', 'Глядач'), ('staff', 'Персонал')], max_length=50, verbose_name='Бажана роль')),
                ('referee_category', models.CharField(blank=True, max_length=100, verbose_name='Суддівська категорія')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('details', models.TextField(blank=True, verbose_name='Додаткові відомості (пояс, ліцензії тощо)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата перевірки')),
                ('review_notes', models.TextField(blank=True, verbose_name='Коментар адміністратора')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_requests', to='accounts.club', verbose_name='Клуб')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Перевірив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запит на верифікацію ролі',
                'verbose_name_plural': 'Запити на верифікацію ролей',
                'db_table': 'role_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
