# Generated by Django 5.2.15 on 2026-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date_user_email_verified_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='role_requests/', verbose_name='Документ підтвердження'),
        ),
    ]
