# Generated by Django 5.2.15 on 2026-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolerequest_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_locked',
            field=models.BooleanField(default=False, verbose_name='ПІБ заблоковано'),
        ),
    ]
