# Generated by Django 5.2.15 on 2026-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_name_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_locked',
            field=models.BooleanField(default=True, verbose_name='ПІБ заблоковано'),
        ),
    ]
