# Generated by Django 5.2.15 on 2026-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_name_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='photo_with_id',
            field=models.FileField(blank=True, null=True, upload_to='role_requests/', verbose_name='Фото з посвідченням'),
        ),
    ]
