# Generated by Django 5.2.15 on 2026-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rolerequest_photo_with_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Максимальна сума боргу перед платформою', verbose_name='Кредитний ліміт комісії (UAH)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_club_leader',
            field=models.BooleanField(default=False, help_text='Дає право сплачувати за всіх членів клубу', verbose_name='Керівник клубу'),
        ),
    ]
