# Generated by Django 5.2.15 on 2026-06-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_ban_reason_user_is_banned'),
        ('accounts', '0008_user_credit_limit_user_is_club_leader'),
    ]

    operations = [
    ]
