# Generated by Django 5.2.14 on 2026-06-25 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260623_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код скидання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('expires_at', models.DateTimeField(verbose_name='Дійсний до')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_code', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Код скидання пароля',
                'verbose_name_plural': 'Коди скидання пароля',
                'db_table': 'password_reset_code',
            },
        ),
    ]
