# Generated by Django 6.0.4 on 2026-04-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('sport_type', models.CharField(help_text='Карате, Дзюдо, Тхеквондо, Грепплінг...', max_length=100, verbose_name='Вид спорту')),
                ('location', models.CharField(max_length=255, verbose_name='Місце проведення')),
                ('start_date', models.DateTimeField(verbose_name='Початок')),
                ('end_date', models.DateTimeField(verbose_name='Завершення')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('registration', 'Реєстрація'), ('active', 'Триває'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
                'db_table': 'tournament',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('allowed_gender', models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча'), ('mixed', 'Змішана')], max_length=10, verbose_name='Допустима стать')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='Мінімальний вік')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='Максимальний вік')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Мін. вага (кг)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Макс. вага (кг)')),
                ('allowed_skill_level', models.CharField(blank=True, max_length=50, verbose_name='Допустимий рівень майстерності')),
                ('bracket_format', models.CharField(choices=[('single_elimination', 'Олімпійська (на вибування)'), ('round_robin', 'Кругова')], default='single_elimination', max_length=50, verbose_name='Формат сітки')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
                'ordering': ['tournament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_number', models.PositiveIntegerField(blank=True, help_text='Встановлюється алгоритмом жеребкування', null=True, verbose_name='Номер посіву')),
                ('recorded_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вага при зважуванні (кг)')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('rejected', 'Відхилено'), ('withdrawn', 'Знято')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='athletes.athlete', verbose_name='Спортсмен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Реєстрація',
                'verbose_name_plural': 'Реєстрації',
                'db_table': 'registration',
                'indexes': [models.Index(fields=['category', 'status'], name='idx_reg_category_status')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'category'), name='uq_registration_athlete_category')],
            },
        ),
    ]
