# Generated by Django 5.2.14 on 2026-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='match_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Перевизначає значення за замовчуванням із рулсету', null=True, verbose_name='Тривалість поєдинку (сек)'),
        ),
        migrations.AddField(
            model_name='category',
            name='ruleset_key',
            field=models.CharField(default='karate_wkf', max_length=50, verbose_name='Ключ рулсету'),
        ),
    ]
