# Generated by Django 5.2.14 on 2026-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_add_ruleset_key_and_match_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='weigh_in_required',
            field=models.BooleanField(default=True, help_text='Якщо вимкнено, учасники автоматично підтверджуються при реєстрації без зважування', verbose_name='Потрібне зважування'),
        ),
    ]
