# Generated by Django 5.2.14 on 2026-05-29 12:22
# Edited: completed_at, registration_start, registration_end already exist in some environments.
# Using SeparateDatabaseAndState with RunSQL conditional DO block to handle both fresh (test) and existing (dev) DBs.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_weigh_in_required'),
    ]

    operations = [
        # ── Fields that might already exist ──────────────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tournament' AND column_name='completed_at') THEN
                            ALTER TABLE tournament ADD COLUMN completed_at timestamp with time zone NULL;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tournament' AND column_name='registration_end') THEN
                            ALTER TABLE tournament ADD COLUMN registration_end timestamp with time zone NULL;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tournament' AND column_name='registration_start') THEN
                            ALTER TABLE tournament ADD COLUMN registration_start timestamp with time zone NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE tournament DROP COLUMN IF EXISTS completed_at;
                    ALTER TABLE tournament DROP COLUMN IF EXISTS registration_end;
                    ALTER TABLE tournament DROP COLUMN IF EXISTS registration_start;
                    """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='tournament',
                    name='completed_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено о'),
                ),
                migrations.AddField(
                    model_name='tournament',
                    name='registration_end',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Кінець реєстрації'),
                ),
                migrations.AddField(
                    model_name='tournament',
                    name='registration_start',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Початок реєстрації'),
                ),
            ],
        ),
        # ── ALTER COLUMN — make weight fields nullable (safe DDL) ────────────
        migrations.AlterField(
            model_name='category',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. вага (кг)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мін. вага (кг)'),
        ),
    ]
