# Generated by Django 5.2.14 on 2026-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_fields_category_optional_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['tournament', 'schedule_order', 'name'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='category',
            name='schedule_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок у розкладі'),
        ),
    ]
