# Generated by Django 5.2.15 on 2026-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_category_options_category_schedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Отримане призове місце (1, 2, 3, 5 тощо) після закінчення змагань у категорії', null=True, verbose_name='Місце в категорії'),
        ),
    ]
