# Generated by Django 5.2.15 on 2026-06-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_registration_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='two_third_places',
            field=models.BooleanField(default=True, help_text='Якщо увімкнено, обидва спортсмени, які програли в півфіналах, отримують 3-є місце.', verbose_name='Два третіх місця'),
        ),
    ]
