# Generated by Django 5.2.15 on 2026-06-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_category_two_third_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='judges_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість суддів для Ката'),
        ),
    ]
