# Generated by Django 5.2.14 on 2026-06-12 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_patronymic_athlete_photo_team'),
        ('tournaments', '0008_category_judges_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='uq_registration_athlete_category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_team',
            field=models.BooleanField(default=False, verbose_name='Групова категорія'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн (Готівка)')], default='offline', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не сплачено'), ('paid', 'Сплачено')], default='unpaid', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='athletes.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='base_registration_fee',
            field=models.PositiveIntegerField(default=500, verbose_name='Базова вартість'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='commission_payer',
            field=models.CharField(choices=[('buyer', 'Покупець'), ('organizer', 'Організатор')], default='buyer', max_length=20, verbose_name='Хто сплачує комісію'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='online_payment_enabled',
            field=models.BooleanField(default=True, verbose_name='Онлайн оплата'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Реквізити для оплати'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform_fee_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сума комісії за офлайн-заявки'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform_fee_status',
            field=models.CharField(choices=[('paid', 'Сплачено'), ('unpaid', 'Не сплачено')], default='paid', max_length=20, verbose_name='Статус оплати комісії'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ruleset_prices',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ціни за рулсети'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='staff_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Робочий персонал'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='athletes.athlete', verbose_name='Спортсмен'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', False)), fields=('athlete', 'category'), name='uq_registration_athlete_category'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'category'), name='uq_registration_team_category'),
        ),
    ]
