# Generated by Django 5.2.14 on 2026-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_registration_uq_registration_athlete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Спортсмен фізично прибув на місце проведення', verbose_name='Явка підтверджена'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='use_check_in',
            field=models.BooleanField(default=False, help_text='Секретар може відмічати прибуття спортсменів на місці', verbose_name='Відмічати явку'),
        ),
    ]
