# Generated by Django 5.2.15 on 2026-06-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_registration_checked_in_tournament_use_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Кількість бійців у команді'),
        ),
    ]
