# Generated by Django 5.2.15 on 2026-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_category_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='registration_fee',
            field=models.PositiveIntegerField(blank=True, help_text='Якщо вказано, перевизначає базову вартість турніру для цієї категорії', null=True, verbose_name='Спеціальна вартість за учасника'),
        ),
    ]
