# Generated by Django 5.2.15 on 2026-06-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_category_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='base_team_registration_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Базова вартість за учасника у командних категоріях'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ruleset_team_prices',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ціни для командних категорій за рулсетами'),
        ),
    ]
