# Generated by Django 5.2.14 on 2026-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_tournament_base_team_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='double_elim_type',
            field=models.CharField(blank=True, choices=[('full', 'Класичний (з Bracket Reset)'), ('short', 'Спрощений (один фінал)')], default='', max_length=10, verbose_name='Тип Double Elimination'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bracket_format',
            field=models.CharField(choices=[('single_elimination', 'Олімпійська (на вибування)'), ('round_robin', 'Кругова'), ('single_repechage', 'Олімпійська сітка з репешажем'), ('double_elimination', 'Double Elimination')], default='single_elimination', max_length=50, verbose_name='Формат сітки'),
        ),
    ]
