# Generated by Django 5.2.15 on 2026-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_category_double_elim_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bracket_format',
            field=models.CharField(choices=[('single_elimination', 'Олімпійська (на вибування)'), ('round_robin', 'Кругова'), ('single_repechage', 'Олімпійська сітка з репешажем'), ('double_elimination', 'Double Elimination'), ('swiss', 'Швейцарська')], default='single_elimination', max_length=50, verbose_name='Формат сітки'),
        ),
    ]
