# Generated by Django 5.2.15 on 2026-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_category_bracket_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='refund_policy',
            field=models.CharField(choices=[('refundable', 'Повернення дозволено'), ('non_refundable', 'Внески не повертаються (штраф 100%)')], default='refundable', max_length=20, verbose_name='Правила повернення внесків'),
        ),
    ]
