# Generated by Django 5.2.15 on 2026-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournament_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='offline_refund_status',
            field=models.CharField(choices=[('none', 'Немає'), ('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено отримання')], default='none', max_length=20, verbose_name='Статус повернення готівки'),
        ),
    ]
