# Generated by Django 5.2.15 on 2026-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournament_chief_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис турніру'),
        ),
    ]
