# Generated by Django 5.2.15 on 2026-06-24 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournament_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judge_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Судді турніру'),
        ),
    ]
